### ISSUE TITLE
github action报错

### ISSUE THREAD

**Issue by zhezhe168** [greats3an/bilibili-toolman#6]
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/bilibili-toolman/bilibili-toolman/bilibili_toolman/__main__.py", line 5, in <module>
    sys.exit(__main__())
  File "/home/runner/work/bilibili-toolman/bilibili-toolman/bilibili_toolman/cli/main.py", line 143, in __main__
    if not setup_session():
  File "/home/runner/work/bilibili-toolman/bilibili-toolman/bilibili_toolman/cli/main.py", line 110, in setup_session
    result = sess.LoginViaUsername(global_args.username,global_args.pwd)        
  File "/home/runner/work/bilibili-toolman/bilibili-toolman/bilibili_toolman/bilisession/common/__init__.py", line 14, in wrapper
    response: Response = classfunc(session, *args, **kwargs)
  File "/home/runner/work/bilibili-toolman/bilibili-toolman/bilibili_toolman/bilisession/client.py", line 251, in LoginViaUsername
    self.login_tokens.update(resp.json()['data']['token_info'])
TypeError: 'NoneType' object is not subscriptable
Error: Process completed with exit code 1.

**Comment by greats3an** [comment]
很可能是账号密码填错了。[加了个 Exception 输出](https://github.com/greats3an/bilibili-toolman/commit/d1d529a194eb9a0150d60eb66a5314f70b2d0a22),再运行一遍看看？

**Comment by zhezhe168** [comment]
解决了，好像是多了个空格，现在有个新问题，说是分区id不对，
[ 2021-08-22 02:45:29 BiliSession  DEBUG ] 准备提交多 P 内容: Panasonic IH調理爐 KY-E227E廚房新趨勢精準大火力料理更安心
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/bilibili-toolman/bilibili-toolman/bilibili_toolman/__main__.py", line 5, in <module>
    sys.exit(__main__())
  File "/home/runner/work/bilibili-toolman/bilibili-toolman/bilibili_toolman/cli/main.py", line 177, in __main__
    result,dirty = upload_sources(sources,arg)
  File "/home/runner/work/bilibili-toolman/bilibili-toolman/bilibili_toolman/cli/main.py", line 92, in upload_sources
    submit_result=sess.SubmitSubmission(submission,seperate_parts=arg.seperate_parts)  
  File "/home/runner/work/bilibili-toolman/bilibili-toolman/bilibili_toolman/bilisession/web.py", line 370, in SubmitSubmission
    result = self._submit_submission(submission.archive).json()
  File "/home/runner/work/bilibili-toolman/bilibili-toolman/bilibili_toolman/bilisession/common/submission.py", line 139, in archive
    "tid": int(self.thread),            
ValueError: invalid literal for int() with base 10: '[76]'
Error: Process completed with exit code 1.

**Comment by greats3an** [comment]
`转载设置，如 --tags [标签,逗号隔开] --thread_id [分区 id,见 README]`，逗号应为半角，方括号不用看的😅
例如 --tags 游戏,单机 --thread_id 17

**Comment by zhezhe168** [comment]
啊这，我再试试

**Comment by zhezhe168** [comment]
前面的问题解决了，新问题又来了。。。
[ 2021-08-22 02:57:48 BiliSession  DEBUG ] 准备提交多 P 内容: Panasonic IH調理爐 KY-E227E廚房新趨勢精準大火力料理更安心
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/bilibili-toolman/bilibili-toolman/bilibili_toolman/__main__.py", line 5, in <module>
    sys.exit(__main__())
  File "/home/runner/work/bilibili-toolman/bilibili-toolman/bilibili_toolman/cli/main.py", line 177, in __main__
    result,dirty = upload_sources(sources,arg)
  File "/home/runner/work/bilibili-toolman/bilibili-toolman/bilibili_toolman/cli/main.py", line 92, in upload_sources
    submit_result=sess.SubmitSubmission(submission,seperate_parts=arg.seperate_parts)  
  File "/home/runner/work/bilibili-toolman/bilibili-toolman/bilibili_toolman/bilisession/web.py", line 370, in SubmitSubmission
    result = self._submit_submission(submission.archive).json()
  File "/home/runner/work/bilibili-toolman/bilibili-toolman/bilibili_toolman/bilisession/client.py", line 153, in _submit_submission
    json={'build': self.BUILD_VER[-1],**submission.archive}
AttributeError: 'dict' object has no attribute 'archive'
Error: Process completed with exit code 1.

**Comment by greats3an** [comment]
[你的fork要更新下了](https://github.com/greats3an/bilibili-toolman/commit/d6c9c77685b317a7afa987cff2ab2ca82d13b57f)
不过这个bug好尴尬😅

**Comment by zhezhe168** [comment]
好的，我再试试
