### ISSUE TITLE
pip安装bilibili_toolman报错。。。

### ISSUE THREAD

**Issue by zhezhe168** [greats3an/bilibili-toolman#8]
Downloading/unpacking bilibili-toolman
  Running setup.py egg_info for package bilibili-toolman
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/build/bilibili-toolman/setup.py", line 1, in <module>
        import setuptools,bilibili_toolman
      File "bilibili_toolman/__init__.py", line 1
    SyntaxError: Non-ASCII character '\xe5' in file bilibili_toolman/__init__.py on line 1, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/build/bilibili-toolman/setup.py", line 1, in <module>

    import setuptools,bilibili_toolman

  File "bilibili_toolman/__init__.py", line 1

SyntaxError: Non-ASCII character '\xe5' in file bilibili_toolman/__init__.py on line 1, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

----------------------------------------
Command python setup.py egg_info failed with error code 1
Storing complete log in /root/.pip/pip.log

**Comment by greats3an** [comment]
[在1.0.5添加了encoding](https://github.com/greats3an/bilibili-toolman/commit/887ef73f5e73d4cf0cce3adb65f982960bda1b9c)
